config/routes.rb
Rails.application.routes.draw do

  root 'projects#index'

  resources :projects, shallow: true do
    resources :notes do
      resources :comments

      member do
        post    'add_tag'
        delete  'remove_tag'
      end

    end
  end

  resources :scaffold_tests

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  # Associations
  belongs_to :note

  # Validations
  validates :text, presence: true

  # Scopes
  default_scope { order(created_at: :asc) }

  # Callbacks

  # Misc
end

app/models/concerns/persisted.rb
module Persisted
  extend ActiveSupport::Concern

  # used primarily to return a collection of comments to display
  # on the notes/show page that does NOT contain the new
  # nil @comment object

  def persisted
    select(&:persisted?)
  end

end

app/models/note.rb
# Stores notes. Notes are parents of comments.
class Note < ActiveRecord::Base
  # Associations
  belongs_to :project
  has_many :comments, dependent: :destroy do
    include Persisted
  end

  # Validations
  validates :project, presence: true
  validates :title, presence: true
  validates :text, presence: true

  # Scopes
  default_scope { order(created_at: :desc) }

  # Callbacks


  # Misc
  acts_as_taggable

  def add_tags(string)
    delim = ActsAsTaggableOn.delimiter
    self.tag_list.add(string, parse: true)
    return string.split(delim)
  end


end

app/models/project.rb
class Project < ActiveRecord::Base
  # Associations
  has_many :notes, dependent: :destroy

  # Validations
  validates :name,  presence: true,
                    uniqueness: true,
                    length: { maximum: 60 }

  # Scopes

  # Callbacks

  # Misc


end

app/models/scaffold_test.rb
class ScaffoldTest < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @note = Note.find(params[:note_id])
    @comment = @note.comments.build(comment_params)

    if @comment.save
      redirect_to @note
    else
      @comments_to_display = @note.comments.persisted
      render 'notes/show'
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:text)
    end


end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
	before_action :set_note_ivar, only: [:show,
																			 :edit,
																			 :update,
																			 :destroy,
																			 :add_tag,
																			 :remove_tag]

	# Shows all notes.
	def index
		@notes = Note.all
	end

	# Shows a specific note.
	def show
		@comment = @note.comments.build
		@comments_to_display = @note.comments.persisted
	end

  # Builds a new note.
  def new
		@project = Project.find(params[:project_id])
    @note = @project.notes.build
  end

  # Creates a new note in the database
  def create
		@project = Project.find(params[:project_id])
  	@note = @project.notes.build(note_params)

    if @note.save
	    flash[:success] = "Note saved."
	    redirect_to note_path(@note)
    else
	    render "new" # the error messages partial will do the rest
    end
  end

	def edit
		@project = @note.project
	end

	def update
		if @note.update(note_params)
			flash[:info] = "Note updated."
			redirect_to note_path(@note)
		else
			flash[:warning] = "Error updating note."
			redirect_to note_path(@note)
		end
	end

	def add_tag
		@new_tags = @note.add_tags(params[:tag_string])

		unless @note.save
			flash[:warning] = "Error adding tag."
		end

		respond_to do |format|
			format.html { redirect_to note_path(@note) }
			format.js
		end

	end

	def remove_tag
		# TODO: refactor this and add_tag, they're basically the same
		@tag_string = params[:tag_string]
		@note.tag_list.remove(@tag_string, parse: true)

		unless @note.save
			flash[:warning] = "Error removing tag."
		end

		respond_to do |format|
			format.html { redirect_to edit_note_path(@note) }
			format.js
		end

	end

	def destroy
		if @note.destroy
			flash[:success] = "Note deleted."
			redirect_to project_path(@note.project)
		end
	end

	  private
			def set_note_ivar
				@note = Note.find(params[:id])
			end

	    def note_params
        params.require(:note).permit(:title, :text, :tag_list) # Whitelist the params to prevent the params from passing any dangerous attributes
	    end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project_ivar, only: [:show, :edit, :update, :destroy]

  helper NotesHelper # to show previews of text

  def index
    @projects = Project.all
  end

  def show
  end

  def new
    @project = Project.new
  end

  def edit
    render "index"
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      flash[:success] = "Project created."
      redirect_to project_path(@project)

    else
      render "new"
    end
  end

  def update
    render "index"
  end

  def destroy
    render "index"
  end

  private
    def set_project_ivar
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:name) # Whitelist the params to prevent the params from passing any dangerous attributes
    end

end

app/controllers/scaffold_tests_controller.rb
class ScaffoldTestsController < ApplicationController
  before_action :set_scaffold_test, only: [:show, :edit, :update, :destroy]

  # GET /scaffold_tests
  # GET /scaffold_tests.json
  def index
    @scaffold_tests = ScaffoldTest.all
  end

  # GET /scaffold_tests/1
  # GET /scaffold_tests/1.json
  def show
  end

  # GET /scaffold_tests/new
  def new
    @scaffold_test = ScaffoldTest.new
  end

  # GET /scaffold_tests/1/edit
  def edit
  end

  # POST /scaffold_tests
  # POST /scaffold_tests.json
  def create
    @scaffold_test = ScaffoldTest.new(scaffold_test_params)

    respond_to do |format|
      if @scaffold_test.save
        format.html { redirect_to @scaffold_test, notice: 'Scaffold test was successfully created.' }
        format.json { render :show, status: :created, location: @scaffold_test }
      else
        format.html { render :new }
        format.json { render json: @scaffold_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scaffold_tests/1
  # PATCH/PUT /scaffold_tests/1.json
  def update
    respond_to do |format|
      if @scaffold_test.update(scaffold_test_params)
        format.html { redirect_to @scaffold_test, notice: 'Scaffold test was successfully updated.' }
        format.json { render :show, status: :ok, location: @scaffold_test }
      else
        format.html { render :edit }
        format.json { render json: @scaffold_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scaffold_tests/1
  # DELETE /scaffold_tests/1.json
  def destroy
    @scaffold_test.destroy
    respond_to do |format|
      format.html { redirect_to scaffold_tests_url, notice: 'Scaffold test was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scaffold_test
      @scaffold_test = ScaffoldTest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scaffold_test_params
      params.require(:scaffold_test).permit(:text, :score)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
  def preview_text(text, length=140)
    if length <= length
      text
    else
      "#{text[0..length]}..."
    end
  end

  def separate_with_commas(text)
    # used to separate tag_list when editing.
    text.split(" ").join(", ")
  end
end

app/views/comments/_comment.html.erb
<div class="panel panel-default" id="comment">
  <div class="panel-body">
    <%= simple_format(comment.text) %>
  </div>
</div>

app/views/layouts/_action_bar.html.erb
<div class="col-sm-2 sidebar">
  <%= yield :action_bar %>
</div>

app/views/layouts/_header.html.erb
  <p></p>
  <nav class="navbar navbar-default">
    <div class="navbar-header">
      <%= link_to "SkyNotes", root_path, class: "navbar-brand" %>
    </div>
    <ul class="nav navbar-nav">
      <li><%= link_to "Projects", projects_path %></li>
    </ul>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SkyNotes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'layouts/header' %>
    <div class="container-fluid">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <div class="row">
	     <%= yield %>
      <%= render 'layouts/action_bar' if :action_bar.present? %>
   </div> <!-- row -->
 </div> <!-- container-fluid -->
</body>
</html>

app/views/notes/_note.html.erb
<h3><%= link_to note.title, note_path(note) %></h3>
<p><%= note.text %></p>
<hr />

app/views/notes/_note_form.html.erb
<% if local_assigns[:edit] %>
  <% url = note_path %>
<% else %>
  <% url = project_notes_path %>
<% end %>

<%= form_for [@project, @note], url: url do |f| %>

    <div class="form-group">
      <%= render 'shared/error_messages', object: f.object %>
    </div>

    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :text %>
      <%= f.text_area :text, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label "Tags" %>
      <%= render "shared/tag_list_edit" %>
    </div>

    <div class="form-group">
      <%= link_to "Cancel", :back, class: "btn" %>
      <%= f.submit 'Post', class: "btn btn-primary" %>
    </div>
<% end %>

app/views/notes/add_tag.js.erb
<% @new_tags.each do |tag| %>
  $("#tags_group").append("<%= j render 'shared/tag_item', tag: tag %>");
<% end %>

$("#tag_string").val("");

app/views/notes/edit.html.erb
<div class="col-sm-12 main">
  <h3>Edit Note</h3>
  <%= render 'notes/note_form', edit: true %>
</div>

app/views/notes/new.html.erb
<div class="col-sm-12 main">
  <h2 class="page-header"><%= link_to @project.name, project_path(@project) %> <small>New Note</small></h2>

  <%= render 'notes/note_form' %>

</div>

app/views/notes/remove_tag.js.erb
$(".tag_group_item:contains('<%= @tag_string %>')").remove();

app/views/notes/show.html.erb
<% content_for :action_bar do %>
  <ul class="nav nav-pills nav-stacked">
    <li class="active"><%= link_to "Edit Note", edit_note_path(@note) %></li>
    <li><%= link_to "Delete Note", @note, method: :delete %></li>
  </ul>

  <h4>Tags</h4>
  <div id="tags_group">
    <%= render "shared/tag_list" %>
  </div>

  <h4>Add Tags</h4>
  <p>Separate tags with commas.</p>
  <%= form_for @note, url: add_tag_note_path(@note), method: :post, remote: true do |f| %>
    <div class="form-group">
      <%= text_field_tag :tag_string, nil, placeholder: "tag, tag, tag" %>
      <%= f.submit "+", class: "btn btn-primary" %>
    </div>
  <% end %>

<% end %>


  <div class="col-sm-10 main">

    <p class="page-header"><%= link_to raw("&laquo; #{@note.project.name}"), project_path(@note.project) %></p>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3><%= @note.title %></h3>
      </div>
      <div class="panel-body">
        <%= simple_format(@note.text) %>
      </div>
    </div>


    <% if @note.comments.count > 0 %>
      <div class="page-header">
        <h3>Comments (<%= @note.comments.count %>)</h3>
      </div>
      <%= render @comments_to_display %>
    <% end %>

    <div class="page-header">
      <h3>New Comment</h3>
    </div>

    <%= form_for [@note, @comment] do |f| %>
        <div class="form-group">
          <%= render 'shared/error_messages', object: f.object %>
        </div>

        <div class="form-group">
          <%= f.text_area :text, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.submit 'Reply', class: "btn btn-primary" %>
        </div>

    <% end %>

  </div>

app/views/projects/_project.html.erb
<tr>
  <td><%= link_to project.name, project_path(project) %></td>
</tr>

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/destroy.html.erb
<h1>Projects#destroy</h1>
<p>Find me in app/views/projects/destroy.html.erb</p>

app/views/projects/edit.html.erb
<h1>Projects#edit</h1>
<p>Find me in app/views/projects/edit.html.erb</p>

app/views/projects/index.html.erb
<div class="col-sm-10 main">
  <h2 class="page-header">Projects</h2>
  <table class="table">
    <thead>
      <tr>
        <th>Project Name</th>
      </tr>
    </thead>
    <tbody>
      <%= render @projects %>
    </tbody>
  </table>
</div>
<% content_for :action_bar do %>
  <ul class="nav nav-pills nav-stacked">
    <li class="active"><%= link_to "New Project", new_project_path %></li>
  </ul>
<% end %>

app/views/projects/new.html.erb
<div class="col-sm-12 main">
  <h2 class="page-header">New Project</h2>

  <%= form_for(@project) do |f| %>
      <div class="form-group">
        <%= render 'shared/error_messages', object: f.object %>
      </div>

      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.submit 'Create', class: "btn btn-primary" %>
      </div>

  <% end %>


</div>

app/views/projects/show.html.erb
<div class="col-sm-10 main">
  <h2 class="page-header"><%= @project.name %></h2>
  <h3>Notes <small><%= pluralize @project.notes.count, "note" %></small></h3>
  <table class="table">
    <thead>
      <tr>
        <th class="col-sm-1">Status</th>
        <th class="col-sm-6">Note</th>
        <th class="col-sm-1">Date</th>
        <th class="col-sm-4">Tags</th>
      </tr>
    </thead>
    <tbody>
    <% @project.notes.each do |note| %>
      <tr>
        <td>*status*</td>
        <td>
          <h4><%= link_to note.title, note_path(note) %></h4>
          <p><%= preview_text note.text %></p>
        </td>
        <td><%= note.created_at.to_formatted_s(:long) %></td>
        <td><%= note.tag_list %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<% content_for :action_bar do %>
  <ul class="nav nav-pills nav-stacked">
    <li class="active"><%= link_to "New Note", new_project_note_path(@project) %></li>
  </ul>
<% end %>

app/views/projects/update.html.erb
<h1>Projects#update</h1>
<p>Find me in app/views/projects/update.html.erb</p>

app/views/scaffold_tests/_form.html.erb
<%= form_for(@scaffold_test) do |f| %>
  <% if @scaffold_test.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scaffold_test.errors.count, "error") %> prohibited this scaffold_test from being saved:</h2>

      <ul>
      <% @scaffold_test.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.number_field :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scaffold_tests/edit.html.erb
<h1>Editing Scaffold Test</h1>

<%= render 'form' %>

<%= link_to 'Show', @scaffold_test %> |
<%= link_to 'Back', scaffold_tests_path %>

app/views/scaffold_tests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Scaffold Tests</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scaffold_tests.each do |scaffold_test| %>
      <tr>
        <td><%= scaffold_test.text %></td>
        <td><%= scaffold_test.score %></td>
        <td><%= link_to 'Show', scaffold_test %></td>
        <td><%= link_to 'Edit', edit_scaffold_test_path(scaffold_test) %></td>
        <td><%= link_to 'Destroy', scaffold_test, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Scaffold test', new_scaffold_test_path %>

app/views/scaffold_tests/new.html.erb
<h1>New Scaffold Test</h1>

<%= render 'form' %>

<%= link_to 'Back', scaffold_tests_path %>

app/views/scaffold_tests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @scaffold_test.text %>
</p>

<p>
  <strong>Score:</strong>
  <%= @scaffold_test.score %>
</p>

<%= link_to 'Edit', edit_scaffold_test_path(@scaffold_test) %> |
<%= link_to 'Back', scaffold_tests_path %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_tag_item.erb
  <div class="tag_item">
    <%= link_to tag,
                "#",
                class: "btn btn-default btn-sm tag_group_item",
                role: "button" %>

  </div>

app/views/shared/_tag_list.html.erb
<% @note.tag_list.each do |tag| %>
  <%= render 'shared/tag_item', tag: tag %>
<% end %>

app/views/shared/_tag_list_edit.html.erb
<!-- Displays tags horizontally, with a "delete" link  -->
<div class="tag_group">
<% @note.tag_list.each do |tag| %>

    <%= link_to "#{tag} <span class='glyphicon glyphicon-remove'></span>".html_safe,
                remove_tag_note_path(@note, tag_string: tag),
                method: :delete,
                remote: true,
                class: "btn btn-default btn-sm tag_group_item",
                role: "button",
                title: "Remove this tag" %>

<% end %>

</div>